# SETUP

In [8]:
# python >= 3.5 version
import sys
assert sys.version_info >= (3,5)

# scikit-learn >= 0.20 is required
import sklearn 
assert sklearn.__version__ >= '0.20'

# tensorflow >=2.0 is required
import tensorflow as tf
assert tf.__version__ >= '2.0'

# import for manipulate data structure
import pandas as pd
import numpy as np
import os

# to make this notebook are stable output accros runs
np.random.seed(42)

#to plot prety figure
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# save the figure automatic
root ='.'
chapter_id = 'ann'
images_path = os.path.join(root,'images',chapter_id)
os.makedirs(images_path,exist_ok=True)

def save_fig(fig_id,tigh_layout=True,fig_extension='png',resolution=300):
    path = os.path.join(images_path,fig_id+'.'+fig_extension)
    print('save figure',fig_id)
    if tigh_layout:
        plt.tight_layout()
    plt.savefig(path,format=fig_extension,resolution=resolution)


In [11]:
# load data from data set
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [15]:
X = iris.data[:,(2,3)]# petal lenght and width
y = (iris.target == 0).astype(np.int) #iris setosa

C:\Users\User\AppData\Local\Temp\ipykernel_7080\2176583148.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = (iris.target == 0).astype(np.int) #iris setosa


In [17]:
per_clf = Perceptron(max_iter=1000,tol=10e-3,random_state=42)
per_clf.fit(X,y)

Perceptron(random_state=42, tol=0.01)

In [20]:
y_pred = per_clf.predict([[2.0 , 0.5]])
y_pred

array([1])

1 => dia termasuk sebuah jenis setosa

In [41]:
per_clf.coef_

array([[-1.4, -2.2]])

In [42]:
per_clf.intercept_

array([4.])