In [59]:
import os 
import matplotlib.pyplot as plt
root = ""
chapter_id = "Multiple_input"
images_path = os.path.join(root,"images",chapter_id)
os.makedirs(images_path,exist_ok=True)
def save_fig(fig_id,tigh_layout=True,fig_extension='png',resolution=True):
    path = os.path.join(images_path,fig_id+'.'+fig_extension)
    print("save figure",fig_id)
    if tigh_layout:
        plt.tight_layout()
    plt.savefig(path,format=fig_extension,resolution=resolution)


In [60]:
import tensorflow as tf 
import keras
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
print(housing["DESCR"])


.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [61]:
# SPLIT DATA TRAIN FULL AND TESTING 
X_train_full,X_test,y_train_full,y_test = train_test_split(housing['data'],housing['target'],random_state=42)
#SPLIT DATA TRAIN FULL TO TRAIN AND VALIDATION
X_train,X_valid,y_train,y_valid = train_test_split(X_train_full,y_train_full,random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.fit_transform(X_valid)
X_test = scaler.fit_transform(X_test)

In [62]:
print(X_train.shape)
print(X_valid.shape)
print(X_test.shape)


(11610, 8)
(3870, 8)
(5160, 8)


In [63]:
print(y_train.shape)
print(y_valid.shape)
print(y_test.shape)

(11610,)
(3870,)
(5160,)


In [64]:
np.random.seed(42)
tf.random.set_seed(42)

In [65]:
# nonsequential model 
input_A = keras.layers.Input(shape=[5],name='wide input')
input_B = keras.layers.Input(shape=[6],name='deep input')
# untuk flow deep pattern menggunakan functional API -> Ex (input_b),(hidden1)
hidden1 = keras.layers.Dense(30,activation='relu')(input_B)
hidden2 = keras.layers.Dense(30,activation='relu')(hidden1)
# untuk flow wide pattern menggunakan concanate function by 2 or more functional API
concat = keras.layers.Concatenate()([input_B,hidden2])
# output layers is used by regresion and regresion output is not activation and one neuron pragesteron
output = keras.layers.Dense(1,name='output')(concat)
model = keras.models.Model(inputs=[input_A,input_B], outputs=[output]) 

In [66]:
pd.DataFrame(X_train[:])

0         1         2         3         4         5         6  \
0     -0.193979 -1.077813 -0.943385  0.014853  0.020733 -0.572916  0.929260   
1      0.751983 -1.868895  0.405478 -0.233277  1.861465  0.205165 -0.916547   
2     -0.414691  0.029701  0.818088  1.056784 -0.087867 -0.299833  1.308729   
3      1.718896 -1.315138  0.326644 -0.219551 -0.337922 -0.111466 -0.982134   
4     -0.962072 -1.236030 -0.056258 -0.031244  1.709059 -0.302570 -0.804112   
...         ...       ...       ...       ...       ...       ...       ...   
11605 -0.814058  0.108810 -0.817233 -0.195044 -0.533220  0.320976 -0.635460   
11606  0.107864  1.690973 -0.261893 -0.135849 -0.231147 -0.191147  0.990163   
11607 -1.223323  0.504350 -0.516003  0.258887  0.452397  0.134491 -0.719786   
11608 -0.935570  1.849189 -0.108785 -0.061589 -0.057751 -0.013545  0.521684   
11609  0.895860  0.187918  0.299475 -0.156707 -0.171827 -0.178234  1.121337   

              7  
0     -1.422155  
1      1.096670  
2     -1.697027  
3      0.941742  
4      1.326562  
...         ...  
11605  0.566917  
11606 -1.447144  
11607  1.146646  
11608 -0.102771  
11609 -1.307209  

[11610 rows x 8 columns]

In [67]:
model.compile(loss= 'mse', optimizer=keras.optimizers.SGD(learning_rate=1e-3))

X_train_A,X_train_B = X_train[:,:5],X_train[:,2:] # 5, 6
X_valid_A, X_valid_B = X_valid[:,:5], X_valid[:,2:] # 5, 6
X_test_A,X_test_B = X_test[:,:5], X_test[:,2:] # 5, 6

history = model.fit([X_train_A,X_train_B],y_train,
                    epochs=20, validation_data=[[X_valid_A,X_valid_B],y_valid])


Epoch 1/20
363/363 [==============================] - 1s 1ms/step - loss: 1.9569 - val_loss: 1.1680
Epoch 2/20
363/363 [==============================] - 0s 920us/step - loss: 1.0952 - val_loss: 1.0192
Epoch 3/20
363/363 [==============================] - 0s 931us/step - loss: 0.9697 - val_loss: 0.9256
Epoch 4/20
363/363 [==============================] - 0s 918us/step - loss: 0.8756 - val_loss: 0.8688
Epoch 5/20
363/363 [==============================] - 0s 928us/step - loss: 0.8072 - val_loss: 0.7991
Epoch 6/20
363/363 [==============================] - 0s 920us/step - loss: 0.7569 - val_loss: 0.8284
Epoch 7/20
363/363 [==============================] - 0s 934us/step - loss: 0.7237 - val_loss: 0.7381
Epoch 8/20
363/363 [==============================] - 0s 917us/step - loss: 0.6975 - val_loss: 0.7340
Epoch 9/20
363/363 [==============================] - 0s 936us/step - loss: 0.6695 - val_loss: 0.7559
Epoch 10/20
363/363 [==============================] - 0s 925us/step - loss: 0.6574 

In [68]:
mse_test = model.evaluate([X_test_A,X_test_B],y_test)

162/162 [==============================] - 0s 676us/step - loss: 0.5738


In [69]:
X_new_A,X_new_B = X_test_A[:3], X_test_B[:3]  
y_pred = model.predict([X_new_A,X_new_B])
y_pred

1/1 [==============================] - 0s 38ms/step


array([[0.53181905],
       [2.40726   ],
       [3.4542665 ]], dtype=float32)

In [70]:
y_test[:3]

array([0.477  , 0.458  , 5.00001])

# Aux Output ( more of one output)

digunakan untuk melakukan sebuah regulaztion pada main output jadi dapat diartikan bahwa set sebuah loss weights main lebih baik daripada loss weights aux out pada proses back progation

In [71]:
# nonsequential model 
input_A = keras.layers.Input(shape=[5],name='wide input')
input_B = keras.layers.Input(shape=[6],name='deep input')
# untuk flow deep pattern menggunakan functional API -> Ex (input_b),(hidden1)
hidden1 = keras.layers.Dense(30,activation='relu')(input_B)
hidden2 = keras.layers.Dense(30,activation='relu')(hidden1)
# untuk flow wide pattern menggunakan concanate function by 2 or more functional API
concat = keras.layers.Concatenate()([input_B,hidden2])
# output layers is used by regresion and regresion output is not activation and one neuron pragesteron
output = keras.layers.Dense(1,name='output')(concat)
aux_output = keras.layers.Dense(1,name='aux_output')(hidden2)
model2 = keras.models.Model(inputs=[input_A,input_B], outputs=[output,aux_output]) 

In [72]:
model2.compile(loss=['mse','mse'],loss_weights=[0.9,0.1],optimizer=keras.optimizers.SGD(learning_rate=1e-3))

In [73]:
# train model with the regulazation (aux output), maka label juga akan di petakan 2
# sebanyak sbeuah output dalam module
history = model2.fit([X_train_A,X_train_B],[y_train,y_train],epochs=20,
                     validation_data=([X_valid_A,X_valid_B],[y_valid,y_valid]))


Epoch 1/20
363/363 [==============================] - 1s 1ms/step - loss: 2.6157 - output_loss: 2.4374 - aux_output_loss: 4.2199 - val_loss: 1.4934 - val_output_loss: 1.3192 - val_aux_output_loss: 3.0608
Epoch 2/20
363/363 [==============================] - 0s 1ms/step - loss: 1.3574 - output_loss: 1.2187 - aux_output_loss: 2.6057 - val_loss: 1.2556 - val_output_loss: 1.1639 - val_aux_output_loss: 2.0805
Epoch 3/20
363/363 [==============================] - 0s 1ms/step - loss: 1.1791 - output_loss: 1.0974 - aux_output_loss: 1.9141 - val_loss: 1.1281 - val_output_loss: 1.0676 - val_aux_output_loss: 1.6728
Epoch 4/20
363/363 [==============================] - 0s 1ms/step - loss: 1.0678 - output_loss: 1.0086 - aux_output_loss: 1.6007 - val_loss: 1.0389 - val_output_loss: 0.9904 - val_aux_output_loss: 1.4760
Epoch 5/20
363/363 [==============================] - 0s 1ms/step - loss: 0.9817 - output_loss: 0.9313 - aux_output_loss: 1.4358 - val_loss: 0.9637 - val_output_loss: 0.9188 - val_aux_

diliha pada hasil bahwa hasil dari loss - output loss bahwa loss lebih generalized daripada output loss dikarenakan pada loss sudah di generalized oleh aux loss

In [78]:
# baiklah untuk menguji pernyataan diatas maka dpt dilakukan sebuah evaluation
total_loss, main_loss, aux_loss = model2.evaluate(
    [X_test_A,X_test_B], [y_test,y_test]
)

162/162 [==============================] - 0s 789us/step - loss: 0.6110 - output_loss: 0.5930 - aux_output_loss: 0.7729


pada hasil bahwa pernyataan diatas sudah teruji benar

In [79]:
y_pred_main,y_pred_aux = model2.predict([X_new_A,X_new_B])

1/1 [==============================] - 0s 51ms/step


In [80]:
y_pred_main

array([[0.57686096],
       [2.2446363 ],
       [3.3115287 ]], dtype=float32)

In [81]:
y_pred_aux

array([[1.0740728],
       [1.9889667],
       [2.9583938]], dtype=float32)

In [82]:
y_test[:3]

array([0.477  , 0.458  , 5.00001])

# Using subclassing API to build dynamic model


In [83]:
class WideAndDeepModel(keras.models.Model):
    #creat the layers
    def __init__(self, units,activation,**kwargs):
        super().__init__(**kwargs)
        self.hidden1 = keras.layers.Dense(units,activation=activation)
        self.hidden2 = keras.layers.Dense(units,activation=activation)
        self.main_output = keras.layers.Dense(1)
        self.aux_output = keras.layers.Dense(1)
    
    # computate the flow connteced between layers
    def call(self,inputs):
        input_A,input_B = inputs
        hidden1 = self.hidden1(input_B)
        hidden2 = self.hidden2(hidden1)
        concat = keras.layers.Concatenate()([input_A,hidden2])
        main_output = self.main_output(concat)
        aux_output = self.aux_output(hidden2)
        return main_output,aux_output
# init
model3 = WideAndDeepModel(units=30, activation='relu')


In [84]:
#call
model3.compile(loss='mse', loss_weights=[0.9,0.1],optimizer=keras.optimizers.SGD(learning_rate=1e-3))


In [85]:
# if want fit -> called the call function on model object 
history = model3.fit([X_train_A,X_train_B],[y_train,y_train],epochs=10,
                    validation_data=[[X_valid_A,X_valid_B],[y_valid,y_valid]])

Epoch 1/10
363/363 [==============================] - 1s 1ms/step - loss: 2.5365 - output_1_loss: 2.3668 - output_2_loss: 4.0632 - val_loss: 1.1481 - val_output_1_loss: 0.9703 - val_output_2_loss: 2.7483
Epoch 2/10
363/363 [==============================] - 0s 1ms/step - loss: 0.9770 - output_1_loss: 0.8205 - output_2_loss: 2.3857 - val_loss: 0.8506 - val_output_1_loss: 0.7332 - val_output_2_loss: 1.9078
Epoch 3/10
363/363 [==============================] - 0s 1ms/step - loss: 0.7780 - output_1_loss: 0.6667 - output_2_loss: 1.7798 - val_loss: 0.7419 - val_output_1_loss: 0.6520 - val_output_2_loss: 1.5505
Epoch 4/10
363/363 [==============================] - 0s 1ms/step - loss: 0.6883 - output_1_loss: 0.5997 - output_2_loss: 1.4861 - val_loss: 0.6868 - val_output_1_loss: 0.6112 - val_output_2_loss: 1.3678
Epoch 5/10
363/363 [==============================] - 0s 1ms/step - loss: 0.6324 - output_1_loss: 0.5550 - output_2_loss: 1.3295 - val_loss: 0.6458 - val_output_1_loss: 0.5757 - val_ou

In [86]:
#call
total_loss, main_loss, aux_loss=model3.evaluate([X_test_A,X_test_B],[y_test,y_test])

162/162 [==============================] - 0s 758us/step - loss: 0.4990 - output_1_loss: 0.4422 - output_2_loss: 1.0101


In [87]:
y_pred_main,y_pred_aux = model3.predict([X_new_A,X_new_B])
y_pred_main

1/1 [==============================] - 0s 47ms/step


array([[0.30790114],
       [1.7951154 ],
       [3.2539742 ]], dtype=float32)

In [88]:
y_pred_aux

array([[0.98200405],
       [1.8633859 ],
       [2.5123062 ]], dtype=float32)

In [89]:
y_test[:3]

array([0.477  , 0.458  , 5.00001])

# saving and restoring

used h5 format hanya bisa untuk save model sequential dan functional api used non sequential model, tidak bisa menyimpan model yang bersifat sub classing

In [91]:
# save the model
model2.save('model2.h5')

In [93]:
# load model
new_model_2 = keras.models.load_model('model2.h5')
new_model_2.summary()

Model: "model_6"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 deep input (InputLayer)        [(None, 6)]          0           []                               
                                                                                                  
 dense_22 (Dense)               (None, 30)           210         ['deep input[0][0]']             
                                                                                                  
 dense_23 (Dense)               (None, 30)           930         ['dense_22[0][0]']               
                                                                                                  
 concatenate_7 (Concatenate)    (None, 36)           0           ['deep input[0][0]',             
                                                                  'dense_23[0][0]']         

In [95]:
# save only weights
model2.save_weights('my_keras_weight_model2.ckpt')

In [96]:
model2.load_weights('my_keras_weight_model2.ckpt')